/*
 * Copyright 2013 Xavier Hosxe
 *
 * Author: Xavier Hosxe (xavier . hosxe (at) gmail . com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "Common.h"
#include "SynthState.h"


const struct OneSynthParams presets[]  = {
        {
                // patch name : 'Preen 2.0'
                // Engine
                { ALGO9, 7, 4, 4} ,
                { 1.5,1.9,1.8,0.7} ,
                { 1, 0, 1, 0} ,
                { 1, 0, 1, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SAW,  OSC_FT_KEYBOARD , 1.0, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , .5, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 2, 0} ,
                { OSC_SHAPE_SIN4, OSC_FT_KEYBOARD , 4, 0} ,
                { OSC_SHAPE_RAND, OSC_FT_KEYBOARD , 6, 0} ,
                { OSC_SHAPE_RAND, OSC_FT_KEYBOARD , 2.5, 0} ,
                // Enveloppe
                { 0,0,1,2.56} ,
                { .5,.5,1,4} ,
                { .1,.5,.6,4} ,
                { .1,.1,.56,2.66} ,
                { 0,.6,0,0.6} ,
                { .1,.5,.6,.3} ,
                // Modulation matrix
                { MATRIX_SOURCE_LFO1, 1, PAN_OSC2, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, MAIN_GATE, 0} ,
                { MATRIX_SOURCE_VELOCITY, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFOENV1, 0, LFO1_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_VELOCITY, 0, INDEX_MODULATION4, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, MTX5_MUL, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFO2, 0, PAN_OSC2, 0} ,
                { MATRIX_SOURCE_LFO3, 0, PAN_OSC1, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SIN, 4.5, 0, 0} ,
                { LFO_SIN, 4.8, 0, 1.0} ,
                { LFO_SIN, 6.0, 0, 4.0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 110, .5,  0, 0}  ,
                { 140, .6, 0, 0},
                {{ 0,7,15,15,15,0,15,15,  0,15,15,15,0,15,15,15}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Preen mk2"
        } ,
        {
                // patch name : 'Preen 2.0'
                // Engine
                { ALGO9, 7, 2, 4} ,
                { 1.0,1.0,1.0,0.7} ,
                { 1, 0, 1, 0} ,
                { 1, 0, 1, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SAW,  OSC_FT_KEYBOARD , 1.0, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , .5, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 2, 0} ,
                { OSC_SHAPE_SIN4, OSC_FT_KEYBOARD , 4, 0} ,
                { OSC_SHAPE_RAND, OSC_FT_KEYBOARD , 6, 0} ,
                { OSC_SHAPE_RAND, OSC_FT_KEYBOARD , 2.5, 0} ,
                // Enveloppe
                { 0,0,1,2.56} ,
                { .5,.5,1,4} ,
                { .1,.5,.6,4} ,
                { .1,.1,.56,2.66} ,
                { 0,.6,0,0.6} ,
                { .1,.5,.6,.3} ,
                // Modulation matrix
                { MATRIX_SOURCE_LFO1, 1, PAN_OSC2, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 0, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_VELOCITY, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFOENV1, 0, LFO1_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_VELOCITY, 0, INDEX_MODULATION4, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, MTX5_MUL, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFO2, 0, PAN_OSC2, 0} ,
                { MATRIX_SOURCE_LFO3, 0, PAN_OSC1, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SIN, 4.5, 0, 0} ,
                { LFO_SIN, 4.8, 0, 1.0} ,
                { LFO_SIN, 6.0, 0, 4.0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, .4,  0, 0}  ,
                { 140, .6, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "SlurpSeq"
        } ,
        {
                // Engine
                { ALGO9, 7, 1, 10} ,
                { .2, .3, .4, .1} ,
                { 1,-1, 1, 0} ,
                { 1, 0, 1, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SQUARE,  OSC_FT_KEYBOARD , 2, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , .5, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 3, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 1, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 1, 0} ,
                { OSC_SHAPE_RAND, OSC_FT_KEYBOARD , 2.5, 0} ,
                // Enveloppe
                { 0.1, .5, 0.6 , .3} ,
                { 0.1, .5, 0.6 , .3} ,
                { 0.1, .5, 0.6 , .3} ,
                { 0.1, .5, 0.6 , .3} ,
                { 0.1, .5, 0.6 , .3} ,
                { 0.1, .5, 0.6 , .3} ,
                // Modulation matrix
                { MATRIX_SOURCE_LFO1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 0, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_VELOCITY, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFOENV1, 0, LFO1_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_VELOCITY, 0, INDEX_MODULATION4, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, MTX5_MUL, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFO2, 0, PAN_OSC2, 0} ,
                { MATRIX_SOURCE_LFO3, 0, PAN_OSC1, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SIN, 2.4, 0, 0} ,
                { LFO_SIN, 4.8, 0, 1.0} ,
                { LFO_SIN, 6.0, 0, 4.0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, .4,  0, 0}  ,
                { 140, .6, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Algo9"
        } ,
        {
                // patch name : 'Preen 2.0'
                // Engine
                { ALGO1, 0, 1, 0} ,
                { 1,0,0,0} ,
                { 1, 0, 1, 0} ,
                { 1, 0, 1, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN,  OSC_FT_KEYBOARD , 2, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 1, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 3, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 4, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 6, 0} ,
                { OSC_SHAPE_RAND, OSC_FT_KEYBOARD , 2.5, 0} ,
                // Enveloppe
                { 2.0, 3.0, 0.8, 3.0} ,
                { 0.1, .5, 0.6 , .3} ,
                { 0.1, .5, 0.6 , .3} ,
                { 0.1, .5, 0.6 , .3} ,
                { 0.1, .5, 0.6 , .3} ,
                { 0.1, .5, 0.6 , .3} ,
                // Modulation matrix
                { MATRIX_SOURCE_LFO1,1.00, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 0, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_VELOCITY, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFOENV1, 0, LFO1_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_VELOCITY, 0, INDEX_MODULATION4, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, MTX5_MUL, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFO2, 0, PAN_OSC2, 0} ,
                { MATRIX_SOURCE_LFO3, 0, PAN_OSC1, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SIN, 2.4, 0, 2.0} ,
                { LFO_SIN, 4.8, 0, 1.0} ,
                { LFO_SIN, 6.0, 0, 4.0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, .4,  0, 0}  ,
                { 140, .6, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "SIN..."
        } ,

        {
                // patch name : 'Preen Seq'
                // Engine
                { ALGO1, 10, 4, 6} ,
                { 16, 21, 0, 0} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 32, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                // Enveloppe
                { 0, 150, 220, 60} ,
                { 100, 65, 150, 100} ,
                { 50, 100, 255, 100} ,
                { 3, 100, 100, 100} ,
                { 0, 150, 160, 60} ,
                { 0, 150, 160, 60} ,
                // Modulation matrix
                { MATRIX_SOURCE_LFOSEQ2, 6, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 64, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 16, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 2, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 2, 0, 1} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 16,  0, 0}  ,
                { 140, 15, 0, 0},
                {{ 12,12,0,0,12,0,0,0,0,0,0,12,0,0,7,7}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Preen Seq"
        } ,
        {
                // patch name : 'Bubble mw'
                // Engine
                { ALGO1, 0, 4, 0} ,
                { 20, 28, 0, 0} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 32, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                // Enveloppe
                { 0, 150, 160, 60} ,
                { 100, 65, 150, 100} ,
                { 50, 100, 255, 100} ,
                { 3, 100, 100, 100} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 2, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 0, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 6, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFO2, 11, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SQUARE, 57, 0, 0} ,
                { LFO_SQUARE, 97, 0, 0} ,
                { LFO_SQUARE, 96, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Bubble  mw"

        },
        {
                // patch name : 'Old and Sad'
                // Engine
                { ALGO1, 0, 4, 0} ,
                { 15, 3, 0, 0} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 32, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 1, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 3, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                // Enveloppe
                { 100, 150, 111, 11} ,
                { 0, 122, 125, 253} ,
                { 50, 100, 255, 100} ,
                { 3, 100, 100, 100} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 2, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 3, OSC2_FREQ, 0} ,
                { MATRIX_SOURCE_LFO2, 3, OSC2_FREQ, 0} ,
                { MATRIX_SOURCE_LFO2, 2, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 23, 0, 0} ,
                { LFO_RANDOM, 40, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Old and Sad"
        },
        {
                // patch name : 'Power'
                // Engine
                { ALGO8, 14, 2, 0} ,
                { 32, 44, 156, 56} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 32, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 48, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 80, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SQUARE, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 4, 0} ,
                // Enveloppe
                { 0, 90, 209, 90} ,
                { 94, 75, 174, 77} ,
                { 0, 179, 0, 173} ,
                { 3, 100, 118, 100} ,
                { 15, 91, 188, 111} ,
                { 0, 130, 87, 108} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 10, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 12, OSC2_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 1, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFO2, 13, INDEX_MODULATION3, 0} ,
                { MATRIX_SOURCE_LFOENV1, 14, LFO2_FREQ, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 11, INDEX_MODULATION3, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 36, 0, 0} ,
                { LFO_SAW, 36, 127, 255} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Power"
        },
        {
                // patch name : 'March Seq'
                // Engine
                { ALGO4, 0, 3, 7} ,
                { 16, 16, 0, 0} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SAW, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 48, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 4, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                // Enveloppe
                { 0, 0, 255, 50} ,
                { 0, 0, 255, 52} ,
                { 0, 101, 255, 255} ,
                { 0, 100, 255, 255} ,
                { 0, 150, 160, 60} ,
                { 0, 150, 160, 60} ,
                // Modulation matrix
                { MATRIX_SOURCE_LFOSEQ1, 2, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFO1, -6, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFO1, 2, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 2, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 1, INDEX_MODULATION3, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 1, 0, 61} ,
                { LFO_SAW, 2, 127, 18} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 8, 0, 0} ,
                { 140, 11, 0, 0} ,
                { { 15, 0, 12, 2, 6, 2, 15, 5, 13, 3, 3, 1, 15, 6, 12, 0} } ,
                { { 15, 0, 1, 4, 15, 0, 15, 0, 15, 0, 3, 7, 15, 0, 10, 11} } ,
                "March Seq"
        },
        {
                // patch name : 'March Seq2'
                // Engine
                { ALGO1, 0, 4, 7} ,
                { 0, 3, 0, 0} ,
                { 114, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SAW, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SAW, OSC_FT_KEYBOARD , 4, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 48, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                // Enveloppe
                { 0, 0, 255, 50} ,
                { 0, 0, 255, 52} ,
                { 0, 101, 255, 255} ,
                { 0, 100, 255, 255} ,
                { 0, 150, 160, 60} ,
                { 0, 150, 160, 60} ,
                // Modulation matrix
                { MATRIX_SOURCE_LFOSEQ1, 4, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 7, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFO1, 3, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, LFOSEQ1_GATE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 1, 18, 61} ,
                { LFO_SAW, 2, 127, 18} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 80, 12, 0, 0} ,
                { 160, 29, 0, 0} ,
                { { 15, 4, 6, 0, 12, 9, 2, 0, 10, 1, 7, 0, 9, 4, 15, 0} } ,
                { { 0, 15, 1, 11, 0, 0, 8, 15, 3, 0, 8, 0, 0, 0, 12, 0} } ,
                "March Seq2"
        },
        {
                // patch name : 'Organ'
                // Engine
                { ALGO6, 0, 3, 0} ,
                { 8, 13, 19, 0} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 32, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                // Enveloppe
                { 70, 89, 145, 60} ,
                { 84, 66, 194, 60} ,
                { 90, 87, 150, 60} ,
                { 0, 0, 255, 255} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 16, INDEX_MODULATION3, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 0, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 36, 0, 0} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Organ"
        },
        {
                // patch name : 'Klong'
                // Engine
                { ALGO4, 8, 3, 0} ,
                { 44, 89, 31, 7} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 24, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 4, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                // Enveloppe
                { 0, 120, 0, 120} ,
                { 0, 130, 0, 130} ,
                { 0, 0, 255, 255} ,
                { 0, 88, 0, 81} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 8, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 11, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_LFO1, 14, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 83, 0, 0} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Klong"
        },
        {
                // patch name : 'Simple Bass'
                // Engine
                { ALGO1, 10, 1, 6} ,
                { 16, 36, 0, 81} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN4, OSC_FT_FIXE, 1, 2} ,
                { OSC_SHAPE_RAND, OSC_FT_KEYBOARD , 3, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                // Enveloppe
                { 0, 253, 0, 49} ,
                { 0, 0, 255, 100} ,
                { 0, 33, 0, 100} ,
                { 3, 100, 100, 100} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 16, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 0, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 36, 0, 0} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Simple Bass"
        },
        {
                // patch name : 'Medieval'
                // Engine
                { ALGO1, 14, 4, 0} ,
                { 27, 28, 0, 0} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 12, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 32, 0} ,
                { OSC_SHAPE_SIN2, OSC_FT_KEYBOARD , 3, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                { OSC_SHAPE_OFF, OSC_FT_KEYBOARD , 0, 0} ,
                // Enveloppe
                { 0, 0, 255, 175} ,
                { 0, 66, 196, 132} ,
                { 50, 100, 255, 210} ,
                { 3, 100, 100, 100} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 6, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 3, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 2, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 38, 0, 117} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Medieval"
        },
        {
                // patch name : 'Crystal Blow'
                // Engine
                { ALGO6, 14, 3, 0} ,
                { 19, 42, 84, 0} ,
                { 96, 128, 87, 30} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN2, OSC_FT_KEYBOARD , 64, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 32, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 24, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 0, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 0, 0} ,
                // Enveloppe
                { 0, 150, 0, 60} ,
                { 0, 0, 255, 48} ,
                { 121, 204, 125, 100} ,
                { 100, 100, 100, 92} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 16, MIX_OSC2, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 13, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFO1, 0, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 36, 0, 0} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Crystal Blow"
        },
        {
                // patch name : '6 osc first'
                // Engine
                { ALGO7, 14, 2, 0} ,
                { 53, 64, 41, 0} ,
                { 88, 128, 113, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 24, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN4, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 4, 0} ,
                { OSC_SHAPE_SQUARE, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 12, 0} ,
                // Enveloppe
                { 0, 80, 173, 60} ,
                { 100, 108, 154, 255} ,
                { 0, 100, 162, 100} ,
                { 79, 100, 171, 100} ,
                { 0, 150, 160, 60} ,
                { 0, 155, 79, 60} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 32, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 12, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOENV1, 16, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 36, 0, 140} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "6 osc first"
        },
        {
                // patch name : 'Old String'
                // Engine
                { ALGO1, 14, 4, 0} ,
                { 0, 36, 0, 0} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN3, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_RAND, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 4, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                // Enveloppe
                { 0, 255, 0, 138} ,
                { 12, 70, 0, 52} ,
                { 0, 100, 129, 255} ,
                { 3, 100, 100, 100} ,
                { 0, 150, 160, 60} ,
                { 0, 150, 160, 60} ,
                // Modulation matrix
                { MATRIX_SOURCE_VELOCITY, 8, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_VELOCITY, 10, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 6, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 9, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 36, 0, 0} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Old String"
        },
        {
                // patch name : 'Metal dream'
                // Engine
                { ALGO1, 8, 4, 6} ,
                { 7, 21, 19, 0} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN4, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 4, -127} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 24, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                // Enveloppe
                { 0, 255, 113, 111} ,
                { 0, 96, 0, 0} ,
                { 0, 208, 139, 109} ,
                { 3, 100, 100, 100} ,
                { 0, 150, 160, 60} ,
                { 0, 150, 160, 60} ,
                // Modulation matrix
                { MATRIX_SOURCE_LFO1, 3, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 22, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 8, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_VELOCITY, 4, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 36, 127, 150} ,
                { LFO_SAW, 16, 0, 0} ,
                { LFO_SAW, 16, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Metal dream"
        },
        {
                // patch name : 'Space Wave'
                // Engine
                { ALGO7, 14, 2, 6} ,
                { 22, 52, 57, 0} ,
                { 128, 88, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN4, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 23, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, -17} ,
                { OSC_SHAPE_SIN3, OSC_FT_KEYBOARD , 48, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                // Enveloppe
                { 127, 83, 217, 166} ,
                { 44, 95, 36, 209} ,
                { 162, 100, 255, 168} ,
                { 53, 113, 137, 255} ,
                { 138, 150, 160, 159} ,
                { 218, 150, 255, 204} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 5, INDEX_MODULATION3, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 23, OSC1_FREQ, 0} ,
                { MATRIX_SOURCE_LFO2, 9, OSC6_FREQ, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 92, MTX3_MUL, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 35, MTX4_MUL, 0} ,
                { MATRIX_SOURCE_MODWHEEL, 127, LFO2_FREQ, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 36, 0, 128} ,
                { LFO_SAW, 72, 127, 6} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Space Wave"
        },
        {
                // patch name : 'Armonica'
                // Engine
                { ALGO1, 14, 4, 6} ,
                { 16, 0, 47, 0} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 32, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                // Enveloppe
                { 60, 180, 160, 71} ,
                { 100, 65, 150, 100} ,
                { 50, 100, 255, 100} ,
                { 3, 100, 100, 100} ,
                { 0, 150, 160, 60} ,
                { 0, 150, 160, 60} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 3, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_LFO1, 1, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ1, 0, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_LFOSEQ2, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 37, 96, 214} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Armonica"

        },
        {
                // patch name : 'Drum 0'
                // Engine
                { ALGO3, 14, 2, 6} ,
                { 82, 0, 116, 197} ,
                { 128, 128, 128, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                // Oscillator
                { OSC_SHAPE_SIN, OSC_FT_FIXE, 1, -28} ,
                { OSC_SHAPE_SQUARE, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_RAND, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 8, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                { OSC_SHAPE_SIN, OSC_FT_KEYBOARD , 16, 0} ,
                // Enveloppe
                { 0, 127, 0, 65} ,
                { 47, 65, 128, 100} ,
                { 0, 0, 255, 90} ,
                { 0, 120, 0, 64} ,
                { 0, 150, 160, 60} ,
                { 0, 150, 160, 60} ,
                // Modulation matrix
                { MATRIX_SOURCE_MODWHEEL, 16, INDEX_MODULATION1, 0} ,
                { MATRIX_SOURCE_PITCHBEND, 16, ALL_OSC_FREQ, 0} ,
                { MATRIX_SOURCE_LFOENV1, 0, INDEX_MODULATION2, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                { MATRIX_SOURCE_NONE, 0, DESTINATION_NONE, 0} ,
                // LFOs
                { LFO_SAW, 36, 0, 0} ,
                { LFO_SAW, 20, 0, 0} ,
                { LFO_SAW, 3, 0, 0} ,
                { .2, 0, 1.0, 1.0} ,
                { 1, .2, .2, 1.0} ,
                { 70, 12,  0, 0}  ,
                { 140, 18, 0, 0},
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "Drum 0"
        },
        {
                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,

                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,

                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,
                { 0,0,0,0} ,

                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,

                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                { 0, 0, 0, 0} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15 ,0}} ,
                {{ 15, 4, 2, 0, 15, 2, 0, 8, 15, 0, 12, 0, 8, 0, 15, 0}} ,
                "*"
        }
};
